version: '3'
services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db